import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Example #1</title> {/* home.specs.ts line 19: the code expects the title to be "Example #1" therefore it is a pass*/}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my home page!</h1>

          <div className={styles.grid}>
            <div className={styles.grid__container} style={{display: 'grid'}}>
              <div className={styles.grid__item}>
                <h2>What Does C.R.U.D stad for?</h2>
              </div>
              <div className={styles.grid__item}>
                <ul>
                <li>Create</li>
                <li>Read</li>
                <li>Update</li>
                <li>Delete</li>
                </ul>
              </div>
            </div>
          </div>

        <div className={styles.grid}>
          <a href="about" className={styles.card}> About Page</a>
          <a href="grades" className={styles.card}> Grades Page</a>
        </div>

        <button> View all this info </button>

        <footer>
        This is an in class example #1
        </footer>

        
      </main>

    </div>
  )
}
